In [ ]:
import cv2 
import time

cap = cv2.VideoCapture(0)
cap.open()

cap.set(cv2.CAP_PROP_FRAME_WIDTH, 240)# 設定擷取影像的尺寸大小
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 360)
def line(frame):
    print (frame)

def pai():

    ret, frame = cap.read(10) # 從攝影機擷取一張影像
   # cv2.imshow('frame', frame) # 顯示圖片
   # cv2.waitKey()
   # cv2.destroyAllWindows()# 關閉所有 OpenCV 視窗
   
    cap.release() # 釋放攝影機
    return frame

while(True):

    frame = pai()
    line(frame)
    time.sleep(10)
    

In [14]:
def white_balance_2(img_input):
    # '''
    # 完美反射白平衡
    # STEP 1：计算每个像素的R\G\B之和
    # STEP 2：按R+G+B值的大小计算出其前Ratio%的值作为参考点的的阈值T
    # STEP 3：对图像中的每个点，计算其中R+G+B值大于T的所有点的R\G\B分量的累积和的平均值
    # STEP 4：对每个点将像素量化到[0,255]之间
    # 依赖ratio值选取而且对亮度最大区域不是白色的图像效果不佳。
    # :param img: cv2.imread读取的图片数据
    # :return: 返回的白平衡结果图片数据
    # '''
    img = img_input.copy()
    b, g, r = cv2.split(img)
    m, n, t = img.shape
    sum_ = np.zeros(b.shape)
    for i in range(m):
        for j in range(n):
            sum_[i][j] = int(b[i][j]) + int(g[i][j]) + int(r[i][j])
    hists, bins = np.histogram(sum_.flatten(), 766, [0, 766])
    Y = 765
    num, key = 0, 0
    ratio = 0.01
    while Y >= 0:
        num += hists[Y]
        if num > m * n * ratio / 100:
            key = Y
            break
        Y = Y - 1
 
    sum_b, sum_g, sum_r = 0, 0, 0
    time = 0
    for i in range(m):
        for j in range(n):
            if sum_[i][j] >= key:
                sum_b += b[i][j]
                sum_g += g[i][j]
                sum_r += r[i][j]
                time = time + 1
 
    avg_b = sum_b / time
    avg_g = sum_g / time
    avg_r = sum_r / time
 
    maxvalue = float(np.max(img))
    # maxvalue = 255
    for i in range(m):
        for j in range(n):
            b = int(img[i][j][0]) * maxvalue / int(avg_b)
            g = int(img[i][j][1]) * maxvalue / int(avg_g)
            r = int(img[i][j][2]) * maxvalue / int(avg_r)
            if b > 255:
                b = 255
            if b < 0:
                b = 0
            if g > 255:
                g = 255
            if g < 0:
                g = 0
            if r > 255:
                r = 255
            if r < 0:
                r = 0
            img[i][j][0] = b
            img[i][j][1] = g
            img[i][j][2] = r
 
    return img


In [61]:
import numpy as np
import cv2

cap = cv2.VideoCapture(0)
#cap.set(cv2.CAP_PROP_FRAME_WIDTH, 240)# 設定擷取影像的尺寸大小
#cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 360)
currentWB = cap.get(cv2.CAP_PROP_WHITE_BALANCE_BLUE_U) 
cap.set(cv2.CAP_PROP_WHITE_BALANCE_BLUE_U, currentWB) 

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
    scr =  frame.copy()
    #scr_3=white_balance_2(scr)
# 轉換BGR到HSV
    brightLAB = cv2.cvtColor(scr, cv2.COLOR_BGR2LAB)

# range of white color in L channel L通道白色範圍
    red = brightLAB[..., 1]
    #mask = cv2.inRange(imgHSV, np.array([156,43,46]), np.array([180, 255, 255]))#选择纯红到衍生红30-40范围
    ret,red_1 = cv2.threshold (red, 130, 255, 0)
    #white_mask = cv2.bitwise_and(scr,scr, mask=red)

    print(red_1)
    #edges = cv2.Canny(white_mask, 40, 140, apertureSize = 3)

    
    cv2.imshow('frame',red_1)
    cv2.imshow('frame1',brightLAB[..., 0])

    if cv2.waitKey(1) & 0xFF == ord('q'):#若检测到按键 ‘q’，退出
        break

# When everything done, release the capture
cap.release()#释放摄像头
cv2.destroyAllWindows()#删除全部窗口


 [  0   0   0 ... 255 255 255]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[  0   

In [ ]:
import cv2
vidcap = cv2.VideoCapture('big_buck_bunny_720p_5mb.mp4')
success,image = vidcap.read()
count = 0
while success:
    cv2.imwrite("frame%d.jpg" % count, image)     # save frame as JPEG file      
      success,image = vidcap.read()
          print('Read a new frame: ', success)
    count += 1

In [ ]:
import os
import cv2

output_directory = 'Output'

#stream = cv2.VideoCapture('http://admin:admin@192.168.1.121/mjpeg.cgi?.mjpeg')
#stream = cv2.VideoCapture('rtsp://admin:Admin2019@192.168.0.65:554/live/av0')
#stream = cv2.VideoCapture('rtsp://admin:AdminAdmin@192.168.0.101:554/live/av0')
stream = cv2.VideoCapture(0)


    
if stream.isOpened():
    print("Successfully connect to camera")
else:
    print("Fail to connect to camera")
    raise SystemExit('Fail to connect to camera')

if os.path.isdir(output_directory) == False:
    os.mkdir(output_directory)
    
frameNo = 0
while (True):
# Capture frame-by-frame
    ret, frame = stream.read()
    if ret == False:
        print("Fail to read one frame")
        break
    else:
# Our operations on the frame come here
		#gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)


        # Display the resulting frame
        scale = 5
        if frameNo % scale  == 0:
            cv2.imshow('hhh',frame)
            name = 'Output\\Img_{:08d}.jpg'.format(int(frameNo/scale) )
            print(name)
            cv2.imwrite(name, frame)
        frameNo = frameNo+1
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
sleep (10)
# When everything done, release the capture
#stream.release()
#cv2.destroyAllWindows()
    
    
  

In [18]:
import cv2
src = cv2.imread('Picture.png')
cv2.imshow('10',src)
cv2.waitKey()
cv2.destroyAllWindows()